@echo off
echo --- starting script vds ---
java -Xmx20g -jar vds.jar "init_db" 
java -Xmx20g -jar vds.jar "load_pan" 
java -Xmx20g -jar vds.jar "process_pan" 
java -Xmx20g -jar vds.jar "build_wvm" 
java -Xmx20g -jar vds.jar "extract_sim" 
java -Xmx20g -jar vds.jar "build_rg1" 
java -Xmx20g -jar vds.jar "build_rg2" 
java -Xmx20g -jar vds.jar "build_rg3" 
java -Xmx20g -jar vds.jar "build_rg4" 
java -Xmx20g -jar vds.jar "rg1" "Degree" 
java -Xmx20g -jar vds.jar "rg1" "Eigenvector Centrality" 
java -Xmx20g -jar vds.jar "rg1" "PageRank" 
java -Xmx20g -jar vds.jar "rg1" "HITS" 
java -Xmx20g -jar vds.jar "rg2" "Degree" 
java -Xmx20g -jar vds.jar "rg2" "Eigenvector Centrality" 
java -Xmx20g -jar vds.jar "rg2" "PageRank" 
java -Xmx20g -jar vds.jar "rg2" "HITS" 
java -Xmx20g -jar vds.jar "rg3" "Degree" 
java -Xmx20g -jar vds.jar "rg3" "Eigenvector Centrality" 
java -Xmx20g -jar vds.jar "rg3" "PageRank" 
java -Xmx20g -jar vds.jar "rg3" "HITS" 
java -Xmx20g -jar vds.jar "rg4" "Degree" 
java -Xmx20g -jar vds.jar "rg4" "Eigenvector Centrality" 
java -Xmx20g -jar vds.jar "rg4" "PageRank" 
java -Xmx20g -jar vds.jar "rg4" "HITS" 
java -Xmx20g -jar vds.jar "build_vg" 
java -Xmx20g -jar vds.jar "training_features0" 
java -Xmx20g -jar vds.jar "test_features0" 
REM java -Xmx20g -jar vds.jar "training_features1" 
REM java -Xmx20g -jar vds.jar "test_features1" 
java -Xmx20g -jar vds.jar "dnn_vemodel" 
cd ../../vds.python 
python sda.py 
cd ../vds/jar 
java -Xmx20g -jar vds.jar "python2table" 
java -Xmx20g -jar vds.jar "join_features" 
java -Xmx20g -jar vds.jar "export2weka" 
java -Xmx20g -jar vds.jar "evaluate_features" 
echo --- script finished ---
